### ISSUE TITLE
Drupal 9 user account not mapping species groups, location of expertise fields

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/drupal-8-modules-indicia_features#3]
I have been tinkering with a new D9 website. Indicia and Easy Login all installed ok and the connection to the warehouse is working. However, 'user account' page does not display the users preferences for What, Where, or Verification (first and last name fields appear as expected and the warehouse id populates).

I tried manually adding the fields using the same name and arrangement from the old D7 site in the hope this might trigger the field to populate and 'Species group' does now present a message "The value of this field is being determined by the _easy_login_allowed_taxon_groups_ function and may not be changed." which suggests it is being identified.

However these fields still do not present any selection options to the user or any apparent error explaining why they are not loading.

Reading the previous sync issue relating to Easy Login i wonder if this is related?

**Comment by JimBacon** [comment]
Hi Ben,

I don't think I've built a D9 site nor done any development of the Easy Login module but thought I would just dip in to the code to see if I could offer anything helpful. There look to be What and Where fields, as you call them, but not Verification.

I've spotted this function
```php
function easy_login_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_register_form' || !hostsite_get_config_value('iform', 'master_checklist_id', 0)) {
    unset($form['field_taxon_groups']);
  }
  if ($form_id === 'user_register_form' || !hostsite_get_config_value('iform', 'profile_location_type_id', 0)) {
    unset($form['field_location']);
  }
  $form['#attached']['library'][] = 'easy_login/user-form';
}
```

Both the `field_taxon_groups` and the `field_location` will be hidden from the registration form but I think will show on the user edit forms provided the following conditions are met
 - The  iform `master_checklist_id` has been set.
 - The  iform `profile_location_type_id` has been set.

Would you like to check those settings are configured and let us know if that helps?

**Comment by JimBacon** [comment]
I should have added that those settings are to be found at the bottom of the settings page, `admin/config/iform/settings`, 
accessible via the menu Configuration > Indicia integration > Indicia settings.

**Comment by benj-d** [comment]
Cheers for the reply Jim and thanks i assumed i was looking in code! The values are not set. I must have omitted to do so when setting up the new site. I'll take a look at the docs and see if i can find what they should be then go from there.

**Comment by benj-d** [comment]
*Update* that's done the job. Master id 15 Checklist populates the taxon groups  as desired and location type id 15 provides VC's
My buggering around with the user edit view has things looking a bit weird but i'll sort that now it's actually populating. Thanks again.
