### ISSUE TITLE
core_version_requirement breaking site

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/drupal-8-modules-indicia_features#6]
Just doing a fresh module install on a D9 site and _uploading_ the current master indicia_features module caused the site to break with the following error;

The 'core_version_requirement' constraint (^10) requires the 'core' key not be set in modules/indicia_features/group_landing_pages/group_landing_pages.info.yml

Removing the core key value (8.x) from that file allowed the site to run with no apparent issues and i can't think of anything it would obviously break on my site though i have not yet tried installing the module or running anything yet.

**Comment by johnvanbreda** [comment]
Is there a reason you are doing a fresh install on Drupal 9 which is now unsupported? But I do agree that the core key should be removed and I'll push that change soon - though the modules are working OK on our D10 sites including fresh installs.

**Comment by benj-d** [comment]
Cheers John, in all honesty the only reason is because I assumed the module didn't work on 10. I think when I'd previously tried I hit version issues and 9 was as high as I could go. Good to know it works on 10, I'll update the site.
